-- This module serves as the root of the `SocialChoice` library.
-- Import modules here that should be built as part of the library.
import SocialChoice.Basic
import SocialChoice.Profile
import SocialChoice.Rank
import SocialChoice.Margin
import SocialChoice.Cycles
import SocialChoice.Meta
import SocialChoice.Rules
import SocialChoice.ListBallot
import SocialChoice.SetExtensions
import SocialChoice.DebordMcGarvey

import SocialChoice.Axioms.Anonymity
import SocialChoice.Axioms.Clones
import SocialChoice.Axioms.Condorcet
import SocialChoice.Axioms.Core
import SocialChoice.Axioms.Dictatorship
import SocialChoice.Axioms.Independence
import SocialChoice.Axioms.Participation
import SocialChoice.Axioms.Resolvability
import SocialChoice.Axioms.Resolute
import SocialChoice.Axioms.Majority
import SocialChoice.Axioms.Monotonicity
import SocialChoice.Axioms.Neutrality
import SocialChoice.Axioms.Pareto
import SocialChoice.Axioms.Reinforcement
import SocialChoice.Axioms.Reversal
import SocialChoice.Axioms.Smith
import SocialChoice.Axioms.Unanimity
import SocialChoice.Axioms.Strategyproofness
import SocialChoice.Axioms.Implications
import SocialChoice.Axioms.InformationalBasis

import SocialChoice.Rules.ScoringRules.Defs
import SocialChoice.Rules.ScoringRules.Anonymity
import SocialChoice.Rules.ScoringRules.Neutrality
import SocialChoice.Rules.ScoringRules.Reinforcement
import SocialChoice.Rules.ScoringRules.Pareto
import SocialChoice.Rules.ScoringRules.Condorcet
import SocialChoice.Rules.ScoringRules.Monotonicity
import SocialChoice.Rules.ScoringRules.Participation
import SocialChoice.Rules.ScoringRules.Plurality.Defs
import SocialChoice.Rules.ScoringRules.Plurality.Involvement
import SocialChoice.Rules.ScoringRules.Plurality.Majority
import SocialChoice.Rules.ScoringRules.Plurality.Pareto
import SocialChoice.Rules.ScoringRules.Plurality.Independence
import SocialChoice.Rules.ScoringRules.Plurality.InformationalBasis
import SocialChoice.Rules.ScoringRules.Plurality.Derived
import SocialChoice.Rules.ScoringRules.Plurality.Reversal
import SocialChoice.Rules.ScoringRules.Borda.Defs
import SocialChoice.Rules.ScoringRules.Borda.C2Borda
import SocialChoice.Rules.ScoringRules.Borda.Condorcet
import SocialChoice.Rules.ScoringRules.Borda.Pareto
import SocialChoice.Rules.ScoringRules.Borda.Monotonicity
import SocialChoice.Rules.ScoringRules.Borda.Independence
import SocialChoice.Rules.ScoringRules.Borda.Majority
import SocialChoice.Rules.ScoringRules.Borda.Reversal
import SocialChoice.Rules.ScoringRules.Borda.InformationalBasis
import SocialChoice.Rules.ScoringRules.Borda.Derived
import SocialChoice.Rules.ScoringRules.Veto.Defs
import SocialChoice.Rules.ScoringRules.Veto.Common
import SocialChoice.Rules.ScoringRules.Veto.Majority
import SocialChoice.Rules.ScoringRules.Veto.Unanimity
import SocialChoice.Rules.ScoringRules.Veto.Independence
import SocialChoice.Rules.ScoringRules.Veto.CondorcetLoser
import SocialChoice.Rules.ScoringRules.Veto.Reversal
import SocialChoice.Rules.ScoringRules.Veto.Derived
import SocialChoice.Rules.ScoringRules.Derived
import SocialChoice.Rules.ScoringElimination.Defs
import SocialChoice.Rules.ScoringElimination.Basic
import SocialChoice.Rules.ScoringElimination.Anonymity
import SocialChoice.Rules.ScoringElimination.Neutrality
import SocialChoice.Rules.ScoringElimination.Monotonicity
import SocialChoice.Rules.ScoringElimination.Pareto
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Defs
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Clones
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Condorcet
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.CondorcetLoser
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.MutualMajority
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Involvement
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Independence
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Reversal
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Derived
import SocialChoice.Rules.ScoringElimination.Baldwin.Defs
import SocialChoice.Rules.ScoringElimination.Baldwin.Condorcet
import SocialChoice.Rules.ScoringElimination.Baldwin.CondorcetLoser
import SocialChoice.Rules.ScoringElimination.Baldwin.InformationalBasis
import SocialChoice.Rules.ScoringElimination.Baldwin.Smith
import SocialChoice.Rules.ScoringElimination.Baldwin.Independence
import SocialChoice.Rules.ScoringElimination.Baldwin.Reversal
import SocialChoice.Rules.ScoringElimination.Baldwin.Derived
import SocialChoice.Rules.ScoringElimination.Coombs.Defs
import SocialChoice.Rules.ScoringElimination.Coombs.Majority
import SocialChoice.Rules.ScoringElimination.Coombs.Condorcet
import SocialChoice.Rules.ScoringElimination.Coombs.CondorcetLoser
import SocialChoice.Rules.ScoringElimination.Coombs.Independence
import SocialChoice.Rules.ScoringElimination.Coombs.Pareto
import SocialChoice.Rules.ScoringElimination.Coombs.NegativeInvolvement
import SocialChoice.Rules.ScoringElimination.Coombs.Reversal
import SocialChoice.Rules.ScoringElimination.Coombs.Derived
import SocialChoice.Rules.Nanson.Defs
import SocialChoice.Rules.Nanson.Condorcet
import SocialChoice.Rules.Nanson.CondorcetLoser
import SocialChoice.Rules.Nanson.Reversal
import SocialChoice.Rules.Nanson.InformationalBasis
import SocialChoice.Rules.Nanson.Independence
import SocialChoice.Rules.Nanson.Neutrality
import SocialChoice.Rules.Nanson.Pareto
import SocialChoice.Rules.Nanson.SubsetReinforcement
import SocialChoice.Rules.Nanson.Involvement
import SocialChoice.Rules.Nanson.Monotonicity
import SocialChoice.Rules.Nanson.Smith
import SocialChoice.Rules.Nanson.Derived
import SocialChoice.Rules.PluralityWithRunoff.Defs
import SocialChoice.Rules.PluralityWithRunoff.Anonymity
import SocialChoice.Rules.PluralityWithRunoff.Neutrality
import SocialChoice.Rules.PluralityWithRunoff.Condorcet
import SocialChoice.Rules.PluralityWithRunoff.CondorcetLoser
import SocialChoice.Rules.PluralityWithRunoff.Pareto
import SocialChoice.Rules.PluralityWithRunoff.Majority
import SocialChoice.Rules.PluralityWithRunoff.Monotonicity
import SocialChoice.Rules.PluralityWithRunoff.Involvement
import SocialChoice.Rules.PluralityWithRunoff.OptimistParticipation
import SocialChoice.Rules.PluralityWithRunoff.Independence
import SocialChoice.Rules.PluralityWithRunoff.SubsetReinforcement
import SocialChoice.Rules.PluralityWithRunoff.EqualsIRVForThreeCandidates
import SocialChoice.Rules.PluralityWithRunoff.Clones
import SocialChoice.Rules.PluralityWithRunoff.Reversal
import SocialChoice.Rules.PluralityWithRunoff.Derived
import SocialChoice.Rules.Minimax.Defs
import SocialChoice.Rules.Minimax.Neutrality
import SocialChoice.Rules.Minimax.Condorcet
import SocialChoice.Rules.Minimax.CondorcetLoser
import SocialChoice.Rules.Minimax.Majority
import SocialChoice.Rules.Minimax.Monotonicity
import SocialChoice.Rules.Minimax.Pareto
import SocialChoice.Rules.Minimax.InformationalBasis
import SocialChoice.Rules.Minimax.Independence
import SocialChoice.Rules.Minimax.IndependenceDominated
import SocialChoice.Rules.Minimax.Reversal
import SocialChoice.Rules.Minimax.Derived
import SocialChoice.Rules.Copeland.Defs
import SocialChoice.Rules.Copeland.Condorcet
import SocialChoice.Rules.Copeland.CondorcetLoser
import SocialChoice.Rules.Copeland.Monotonicity
import SocialChoice.Rules.Copeland.InformationalBasis
import SocialChoice.Rules.Copeland.Pareto
import SocialChoice.Rules.Copeland.Neutrality
import SocialChoice.Rules.Copeland.Involvement
import SocialChoice.Rules.Copeland.Independence
import SocialChoice.Rules.Copeland.Smith
import SocialChoice.Rules.Copeland.Reversal
import SocialChoice.Rules.Copeland.Derived
import SocialChoice.Rules.Black.Defs
import SocialChoice.Rules.Black.Neutrality
import SocialChoice.Rules.Black.Condorcet
import SocialChoice.Rules.Black.CondorcetLoser
import SocialChoice.Rules.Black.Smith
import SocialChoice.Rules.Black.Pareto
import SocialChoice.Rules.Black.Monotonicity
import SocialChoice.Rules.Black.InformationalBasis
import SocialChoice.Rules.Black.Involvement
import SocialChoice.Rules.Black.Independence
import SocialChoice.Rules.Black.SubsetReinforcement
import SocialChoice.Rules.Black.Reversal
import SocialChoice.Rules.Black.Derived
import SocialChoice.Rules.DefensibleSet.Defs
import SocialChoice.Rules.UncoveredSet.Defs
import SocialChoice.Rules.UncoveredSet.Smith
import SocialChoice.Rules.UncoveredSet.InformationalBasis
import SocialChoice.Rules.UncoveredSet.SingletonReversal
import SocialChoice.Rules.UncoveredSet.Reversal
import SocialChoice.Rules.UncoveredSet.Pareto
import SocialChoice.Rules.UncoveredSet.Neutrality
import SocialChoice.Rules.UncoveredSet.Clones
import SocialChoice.Rules.UncoveredSet.Derived
import SocialChoice.Rules.TopCycle.Defs
import SocialChoice.Rules.TopCycle.Condorcet
import SocialChoice.Rules.TopCycle.CondorcetLoser
import SocialChoice.Rules.TopCycle.MutualMajority
import SocialChoice.Rules.TopCycle.Neutrality
import SocialChoice.Rules.TopCycle.Clones
import SocialChoice.Rules.TopCycle.Pareto
import SocialChoice.Rules.TopCycle.Reversal
import SocialChoice.Rules.TopCycle.Derived
import SocialChoice.Rules.SplitCycle.Defs
import SocialChoice.Rules.SplitCycle.Clones
import SocialChoice.Rules.SplitCycle.Condorcet
import SocialChoice.Rules.SplitCycle.Smith
import SocialChoice.Rules.SplitCycle.Involvement
import SocialChoice.Rules.SplitCycle.Monotonicity
import SocialChoice.Rules.SplitCycle.Neutrality
import SocialChoice.Rules.SplitCycle.Independence
import SocialChoice.Rules.SplitCycle.Pareto
import SocialChoice.Rules.SplitCycle.Reversal
import SocialChoice.Rules.SplitCycle.InformationalBasis
import SocialChoice.Rules.SplitCycle.Derived
import SocialChoice.Rules.Schulze.Defs
import SocialChoice.Rules.Schulze.Path
import SocialChoice.Rules.Schulze.Transitivity
import SocialChoice.Rules.Schulze.RefinesSplitCycle
import SocialChoice.Rules.Schulze.Clones
import SocialChoice.Rules.Schulze.Neutrality
import SocialChoice.Rules.Schulze.Independence
import SocialChoice.Rules.Schulze.Monotonicity
import SocialChoice.Rules.Schulze.Reversal
import SocialChoice.Rules.Schulze.InformationalBasis
import SocialChoice.Rules.Schulze.Derived
import SocialChoice.Rules.River.Defs
import SocialChoice.Rules.River.Basic
import SocialChoice.Rules.River.RefinesSplitCycle
import SocialChoice.Rules.River.Derived

import SocialChoice.Impossibilities.CondorcetStrategyproofness
import SocialChoice.Impossibilities.CondorcetParticipation
import SocialChoice.Impossibilities.CondorcetReinforcement
import SocialChoice.Impossibilities.CondorcetReinforcementN8.Main
import SocialChoice.Impossibilities.AnonymousNeutralResolute
import SocialChoice.Impossibilities.GibbardSatterthwaite.Main
import SocialChoice.Impossibilities.DugganSchwartz.Main
import SocialChoice.Impossibilities.Holliday.Main
