-- This module serves as the root of the `SocialChoice` library.
-- Import modules here that should be built as part of the library.
import SocialChoice.Basic
import SocialChoice.Profile
import SocialChoice.Rank
import SocialChoice.Margin
import SocialChoice.Cycles
import SocialChoice.Rules
import SocialChoice.ListBallot
import SocialChoice.SetExtensions

import SocialChoice.Axioms.Anonymity
import SocialChoice.Axioms.Clones
import SocialChoice.Axioms.Condorcet
import SocialChoice.Axioms.Core
import SocialChoice.Axioms.Independence
import SocialChoice.Axioms.Participation
import SocialChoice.Axioms.Majority
import SocialChoice.Axioms.Monotonicity
import SocialChoice.Axioms.Neutrality
import SocialChoice.Axioms.Pareto
import SocialChoice.Axioms.Reinforcement
import SocialChoice.Axioms.Unanimity
import SocialChoice.Axioms.Strategyproofness

import SocialChoice.Rules.ScoringRules.Anonymity
import SocialChoice.Rules.ScoringRules.Neutrality
import SocialChoice.Rules.ScoringRules.Reinforcement
import SocialChoice.Rules.ScoringRules.Pareto
import SocialChoice.Rules.ScoringRules.Condorcet
import SocialChoice.Rules.ScoringRules.Monotonicity
import SocialChoice.Rules.ScoringRules.Participation
import SocialChoice.Rules.ScoringRules.Plurality.Defs
import SocialChoice.Rules.ScoringRules.Plurality.Involvement
import SocialChoice.Rules.ScoringRules.Plurality.Majority
import SocialChoice.Rules.ScoringRules.Plurality.Pareto
import SocialChoice.Rules.ScoringRules.Borda.Defs
import SocialChoice.Rules.ScoringRules.Borda.C2Borda
import SocialChoice.Rules.ScoringRules.Borda.Condorcet
import SocialChoice.Rules.ScoringRules.Borda.Pareto
import SocialChoice.Rules.ScoringRules.Borda.Monotonicity
import SocialChoice.Rules.ScoringRules.Borda.Majority
import SocialChoice.Rules.ScoringRules.Borda.Reversal
import SocialChoice.Rules.ScoringRules.Veto.Defs
import SocialChoice.Rules.ScoringRules.Veto.Majority
import SocialChoice.Rules.ScoringElimination.Defs
import SocialChoice.Rules.ScoringElimination.Basic
import SocialChoice.Rules.ScoringElimination.Neutrality
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Defs
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.Clones
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.CondorcetLoser
import SocialChoice.Rules.ScoringElimination.InstantRunoffVoting.MutualMajority
import SocialChoice.Rules.ScoringElimination.Baldwin.Defs
import SocialChoice.Rules.ScoringElimination.Baldwin.Condorcet
import SocialChoice.Rules.ScoringElimination.Baldwin.CondorcetLoser
import SocialChoice.Rules.ScoringElimination.Coombs.Defs
import SocialChoice.Rules.ScoringElimination.Coombs.Majority
import SocialChoice.Rules.Nanson.Defs
import SocialChoice.Rules.Nanson.Condorcet
import SocialChoice.Rules.Nanson.CondorcetLoser
import SocialChoice.Rules.Nanson.Reversal
import SocialChoice.Rules.PluralityWithRunoff.Defs
import SocialChoice.Rules.PluralityWithRunoff.CondorcetLoser
import SocialChoice.Rules.PluralityWithRunoff.Pareto
import SocialChoice.Rules.PluralityWithRunoff.Majority
import SocialChoice.Rules.PluralityWithRunoff.Involvement
import SocialChoice.Rules.Minimax.Defs
import SocialChoice.Rules.Minimax.Condorcet
import SocialChoice.Rules.Minimax.Monotonicity
import SocialChoice.Rules.Black.Defs
import SocialChoice.Rules.Black.Condorcet
import SocialChoice.Rules.Black.CondorcetLoser
import SocialChoice.Rules.Black.Pareto
import SocialChoice.Rules.Black.Monotonicity
import SocialChoice.Rules.SplitCycle.Defs
import SocialChoice.Rules.SplitCycle.Clones
import SocialChoice.Rules.SplitCycle.Condorcet
import SocialChoice.Rules.SplitCycle.Involvement
import SocialChoice.Rules.SplitCycle.Monotonicity
import SocialChoice.Rules.SplitCycle.Pareto
import SocialChoice.Rules.SplitCycle.Reversal
import SocialChoice.Rules.Schulze.Defs
import SocialChoice.Rules.Schulze.Path
import SocialChoice.Rules.Schulze.Transitivity
import SocialChoice.Rules.Schulze.RefinesSplitCycle

import SocialChoice.Impossibilities.CondorcetStrategyproofness
import SocialChoice.Impossibilities.CondorcetParticipation
import SocialChoice.Impossibilities.CondorcetReinforcement
import SocialChoice.Impossibilities.GibbardSatterthwaite.Main
import SocialChoice.Impossibilities.DugganSchwartz.Main
